# Generated by Django 2.2.3 on 2019-08-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(max_length=150)),
                ('customer_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StripePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=150)),
                ('nickname', models.CharField(max_length=150)),
                ('interval', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_stripe.StripeProduct')),
            ],
        ),
    ]
