# Generated by Django 2.2.3 on 2019-08-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
