# Generated by Django 2.2.3 on 2019-08-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0002_stripecustomer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_stripe.StripeCustomer')),
                ('items', models.ManyToManyField(to='django_rest_stripe.StripeProduct')),
            ],
        ),
    ]
