# Generated by Django 2.2.3 on 2019-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0003_stripesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='items',
            field=models.ManyToManyField(related_name='items', to='django_rest_stripe.StripePlan'),
        ),
    ]
