# Generated by Django 2.2.3 on 2019-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0004_auto_20190820_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=6),
        ),
    ]
