# Generated by Django 2.2.3 on 2019-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0005_auto_20190822_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeplan',
            name='status',
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
