# Generated by Django 2.2.3 on 2019-09-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0006_auto_20190822_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
