# Generated by Django 2.2.3 on 2019-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0007_stripecustomer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
