# Generated by Django 2.2.3 on 2019-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0008_stripeplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
