# Generated by Django 2.2.3 on 2019-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0009_stripesubscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeplan',
            name='interval',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('quarterly', 'quarterly')], max_length=6),
        ),
    ]
