# Generated by Django 2.2.3 on 2019-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0011_auto_20191023_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='display_frequency',
            field=models.CharField(default='montly', max_length=20),
        ),
        migrations.AddField(
            model_name='stripeplan',
            name='display_price',
            field=models.CharField(default='0.00', max_length=20),
        ),
        migrations.AlterField(
            model_name='stripeplan',
            name='description',
            field=models.TextField(blank=True, default='enter description', null=True),
        ),
    ]
