# Generated by Django 2.2.3 on 2019-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0012_auto_20191108_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='header_frequency',
            field=models.CharField(default='Billed Monthly', max_length=100),
        ),
    ]
