# Generated by Django 2.2.3 on 2019-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_stripe', '0013_stripeplan_header_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeplan',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
